"""Added applied date to table

Revision ID: 26aa32005fbc
Revises: 18e91ad65f3b
Create Date: 2025-04-29 14:03:27.672714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26aa32005fbc'
down_revision = '18e91ad65f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_applied', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('date_applied')

    # ### end Alembic commands ###
