"""Added indexes

Revision ID: 6e0e59a8247c
Revises: 817e242cf2d9
Create Date: 2025-04-29 15:41:25.529023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e0e59a8247c'
down_revision = '817e242cf2d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_date_applied'), ['date_applied'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_salary'), ['salary'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_status'))
        batch_op.drop_index(batch_op.f('ix_application_salary'))
        batch_op.drop_index(batch_op.f('ix_application_date_applied'))

    # ### end Alembic commands ###
