"""Added applied date to table with nullable

Revision ID: 817e242cf2d9
Revises: 26aa32005fbc
Create Date: 2025-04-29 14:05:18.559300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817e242cf2d9'
down_revision = '26aa32005fbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_applied', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('date_applied')

    # ### end Alembic commands ###
