"""initial migration

Revision ID: d5fdc865f037
Revises: 
Create Date: 2025-03-17 14:51:47.406789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5fdc865f037'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_student')
    op.drop_table('student')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('studentId', sa.INTEGER(), nullable=False),
    sa.Column('firstName', sa.VARCHAR(length=80), nullable=True),
    sa.Column('lastName', sa.VARCHAR(length=80), nullable=True),
    sa.PrimaryKeyConstraint('studentId')
    )
    op.create_table('_alembic_tmp_student',
    sa.Column('firstName', sa.VARCHAR(length=80), nullable=True),
    sa.Column('lastName', sa.VARCHAR(length=80), nullable=True),
    sa.Column('studentID', sa.INTEGER(), nullable=False)
    )
    # ### end Alembic commands ###
